# Generated by Django 3.1.2 on 2020-10-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.CharField(max_length=10, null=True)),
                ('tname', models.CharField(max_length=50, null=True)),
                ('tmin', models.FloatField()),
                ('tmax', models.FloatField()),
                ('treference', models.CharField(max_length=50, null=True)),
                ('tunit', models.CharField(max_length=50, null=True)),
                ('tdoctor', models.CharField(max_length=50, null=True)),
                ('tdescription', models.TextField(null=True)),
                ('thigh_d', models.CharField(max_length=50, null=True)),
                ('tlow_d', models.CharField(max_length=50, null=True)),
                ('thigh_advice', models.TextField(null=True)),
                ('tlow_advice', models.TextField(null=True)),
            ],
        ),
    ]
