# Generated by Django 3.1.2 on 2020-10-28 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SARZS', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='thigh_d',
            new_name='thigh_disease',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='tlow_d',
            new_name='tlow_disease',
        ),
    ]
