# Generated by Django 3.1.2 on 2020-10-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SARZS', '0002_auto_20201028_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='diagnostic_centers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.CharField(max_length=10, null=True)),
                ('dname', models.CharField(max_length=200, null=True)),
                ('dtype', models.CharField(max_length=50, null=True)),
                ('daddress', models.CharField(max_length=200, null=True)),
                ('dcontact', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='hospitals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hid', models.CharField(max_length=10, null=True)),
                ('hname', models.CharField(max_length=200, null=True)),
                ('htype', models.CharField(max_length=50, null=True)),
                ('haddress', models.CharField(max_length=200, null=True)),
                ('hcontact', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
