# Generated by Django 3.1.2 on 2020-10-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SARZS', '0003_diagnostic_centers_hospitals'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic_centers',
            name='dweb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hospitals',
            name='hweb',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
