# Generated by Django 3.1.2 on 2020-10-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SARZS', '0004_auto_20201029_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docid', models.CharField(max_length=10, null=True)),
                ('docname', models.CharField(max_length=100, null=True)),
                ('docdesignation', models.CharField(max_length=200, null=True)),
                ('tdoctor', models.CharField(max_length=200, null=True)),
                ('doccontact', models.CharField(max_length=200, null=True)),
                ('docchamber', models.CharField(max_length=200, null=True)),
                ('docrating', models.FloatField()),
                ('docTotalRating', models.FloatField()),
                ('docNumRating', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='test',
            name='tdoctor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='thigh_disease',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='tlow_disease',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='tname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='treference',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='tunit',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
