# Generated by Django 3.1.2 on 2020-10-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SARZS', '0005_auto_20201029_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='docchamber',
        ),
        migrations.AddField(
            model_name='doctor',
            name='docaddress',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='diagnostic_centers',
            name='daddress',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='hospitals',
            name='haddress',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
