# Generated by Django 3.1.2 on 2020-10-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SARZS', '0006_auto_20201029_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruser', models.CharField(max_length=100)),
                ('rdate', models.DateTimeField()),
                ('tname', models.CharField(max_length=100, null=True)),
                ('tlavel', models.FloatField()),
                ('treference', models.CharField(max_length=100, null=True)),
                ('rcomment', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
