# Generated by Django 3.1.2 on 2020-10-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SARZS', '0007_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='rdate',
            field=models.DateField(),
        ),
    ]
