# Generated by Django 3.1.2 on 2020-11-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SARZS', '0008_auto_20201029_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='docqualification',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
