# Generated by Django 3.1.2 on 2020-11-08 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SARZS', '0009_doctor_docqualification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='doctor',
            new_name='doctor_list',
        ),
    ]
