# Generated by Django 3.1.2 on 2020-11-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SARZS', '0010_auto_20201108_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='rdate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
