# Generated by Django 3.1.2 on 2020-11-08 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SARZS', '0011_auto_20201108_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='tlavel',
            new_name='tlevel',
        ),
    ]
