# Generated by Django 3.1.2 on 2020-11-18 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SARZS', '0013_hospitals_hdivision'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitals',
            old_name='haddress',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='hospitals',
            old_name='hcontact',
            new_name='Contact',
        ),
        migrations.RenameField(
            model_name='hospitals',
            old_name='hdivision',
            new_name='Division',
        ),
        migrations.RenameField(
            model_name='hospitals',
            old_name='hid',
            new_name='Hid',
        ),
        migrations.RenameField(
            model_name='hospitals',
            old_name='hname',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='hospitals',
            old_name='htype',
            new_name='Type',
        ),
        migrations.RenameField(
            model_name='hospitals',
            old_name='hweb',
            new_name='Website',
        ),
    ]
