# Generated by Django 3.1.3 on 2020-11-18 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SARZS', '0015_auto_20201118_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='tname',
            new_name='Test_Name',
        ),
    ]
