# Generated by Django 3.1.2 on 2020-11-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SARZS', '0019_diagnostic_centers_division'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor_list',
            old_name='docaddress',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='doctor_list',
            old_name='doccontact',
            new_name='Contact',
        ),
        migrations.RenameField(
            model_name='doctor_list',
            old_name='docid',
            new_name='DOCid',
        ),
        migrations.RenameField(
            model_name='doctor_list',
            old_name='docdesignation',
            new_name='Designation',
        ),
        migrations.RenameField(
            model_name='doctor_list',
            old_name='docname',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='doctor_list',
            old_name='docNumRating',
            new_name='NumRating',
        ),
        migrations.RenameField(
            model_name='doctor_list',
            old_name='docqualification',
            new_name='Qualification',
        ),
        migrations.RenameField(
            model_name='doctor_list',
            old_name='docTotalRating',
            new_name='Rating',
        ),
        migrations.RenameField(
            model_name='doctor_list',
            old_name='docrating',
            new_name='TotalRating',
        ),
        migrations.AddField(
            model_name='doctor_list',
            name='Area',
            field=models.CharField(choices=[('Barishal', 'Barishal '), ('Chittagong', 'Chittagong '), ('Dhaka', 'Dhaka'), ('Mymensingh', 'Mymensingh'), ('Khulna', 'Khulna'), ('Rajshahi', 'Rajshahi'), ('Rangpur', 'Rangpur'), ('Sylhet', 'Sylhet')], max_length=50, null=True),
        ),
    ]
