# Generated by Django 3.1.2 on 2020-11-19 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SARZS', '0020_auto_20201119_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnostic_centers',
            old_name='Division',
            new_name='Area',
        ),
        migrations.RenameField(
            model_name='hospitals',
            old_name='Division',
            new_name='Area',
        ),
    ]
