# Generated by Django 3.1.2 on 2020-12-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SARZS', '0024_hospitals_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic_centers',
            name='photo',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
