# Generated by Django 3.1.2 on 2020-12-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SARZS', '0025_diagnostic_centers_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_list',
            name='photo',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
