# Generated by Django 3.1.2 on 2020-12-07 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SARZS', '0027_auto_20201206_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='docReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(null=True)),
                ('rating', models.FloatField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='docComment',
        ),
        migrations.RemoveField(
            model_name='doctor_list',
            name='NumRating',
        ),
        migrations.RemoveField(
            model_name='doctor_list',
            name='Rating',
        ),
        migrations.RemoveField(
            model_name='doctor_list',
            name='TotalRating',
        ),
        migrations.AddField(
            model_name='docreview',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SARZS.doctor_list'),
        ),
        migrations.AddField(
            model_name='docreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
