# Generated by Django 3.1.2 on 2020-12-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SARZS', '0028_auto_20201207_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_list',
            name='rating',
            field=models.FloatField(null=True),
        ),
    ]
