# Generated by Django 3.1.2 on 2020-12-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SARZS', '0030_auto_20201207_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_list',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
