# Generated by Django 3.1.2 on 2020-12-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SARZS', '0031_auto_20201207_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='diagnosticReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Did', models.CharField(max_length=10, null=True)),
                ('user', models.CharField(max_length=100, null=True)),
                ('comment', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='hospitalReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hid', models.CharField(max_length=10, null=True)),
                ('user', models.CharField(max_length=100, null=True)),
                ('comment', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='diagnosticComment',
        ),
        migrations.DeleteModel(
            name='hospitalComment',
        ),
        migrations.RemoveField(
            model_name='diagnostic_centers',
            name='NumRating',
        ),
        migrations.RemoveField(
            model_name='hospitals',
            name='NumRating',
        ),
        migrations.AddField(
            model_name='diagnostic_centers',
            name='numberOfRating',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospitals',
            name='numberOfRating',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='doctor_list',
            name='numberOfRating',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
