# Generated by Django 3.1.2 on 2020-12-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SARZS', '0032_auto_20201207_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='tdoctor',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
